// Synthetic browser journeys. Set FRAMEKEEP_PLAYWRIGHT_PATH to an existing
// globally provisioned Playwright module; this test never installs dependencies.
import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';

test('synthetic desktop user journeys, themes and scaled layout', {skip:!process.env.FRAMEKEEP_PLAYWRIGHT_PATH,timeout:120000}, async()=>{
  const {chromium}=await import(pathToFileURL(process.env.FRAMEKEEP_PLAYWRIGHT_PATH).href);
  const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../extension');
  const server=http.createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser;
  try{
    browser=await chromium.launch({headless:true,...(process.env.FRAMEKEEP_BROWSER_PATH?{executablePath:process.env.FRAMEKEEP_BROWSER_PATH}:{})});
    const page=await browser.newPage({viewport:{width:1108,height:570}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.addInitScript(()=>{
      const cues=Array.from({length:80},(_,i)=>({start:i*3,end:i*3+2.8,text:i===2?'Xin chào — a multilingual transcript.':`Authored synthetic segment ${i+1}. This transcript has a readable line and original source timing.`}));
      const wav=new Uint8Array(80044),wv=new DataView(wav.buffer);const put=(at,str)=>[...str].forEach((c,i)=>wav[at+i]=c.charCodeAt(0));put(0,'RIFF');wv.setUint32(4,80036,true);put(8,'WAVEfmt ');wv.setUint32(16,16,true);wv.setUint16(20,1,true);wv.setUint16(22,1,true);wv.setUint32(24,8000,true);wv.setUint32(28,8000,true);wv.setUint16(32,1,true);wv.setUint16(34,8,true);put(36,'data');wv.setUint32(40,80000,true);wav.fill(128,44);let raw='';for(let i=0;i<wav.length;i+=8192)raw+=String.fromCharCode(...wav.subarray(i,i+8192));const audio='data:audio/wav;base64,'+btoa(raw);
      const base={bytes:12000,created:100,finished:200,sourceUrl:'https://example.test/media',previewUrl:audio,capabilities:{verified:true,kind:'audio',hasAudio:true,hasVideo:false,playback:true,speech:true,visual:false}};
      const generated={id:'generated',status:'ready',source:'generated',language:'vi',cues,timed:true,coverage:'Whole saved file'};
      const items=[{...base,id:'one',title:'Authored speech',filename:'speech.wav',kind:'audio',transcript:{status:'unavailable'},transcriptTracks:[generated,{id:'untimed',status:'ready',source:'imported',language:'en',text:'Original untimed text, preserved without invented timestamps.',timed:false}]},{...base,id:'two',title:'Second recording',filename:'second.wav',kind:'video',capabilities:{...base.capabilities,kind:'video',hasVideo:true}},{id:'image',title:'Synthetic image',filename:'image.png',kind:'image',capabilities:{kind:'image',hasAudio:false,playback:false,speech:false,visual:false}}];
      let state={helper:{status:'ready',directory:'Synthetic save folder'},settings:{appearance:'system',transcriptTextSize:16,tourState:'new',notifications:true,repeat:'none',controlsIntroSeen:false},library:items,collections:[{id:'collection',name:'Examples',itemIds:['two','one']}],jobs:[{id:'child',sourceItemId:'one',action:'study',status:'evidence_ready',title:'Generated speech',studyJobId:'child'}],capabilities:{study:{available:true}},selectedItem:null,probe:{status:'idle'},study:{status:'idle'},app:{version:'synthetic-test'}};
      let revision=1;window.testMessages=[];window.testState=()=>state;window.testChange=fn=>{fn(state);revision++;};
      window.pywebview={api:{snapshot:async previous=>previous===revision?null:{revision,state:structuredClone(state)},dispatch:async message=>{window.testMessages.push(message);const find=id=>state.library.find(item=>item.id===id);if(message.action==='settings')Object.assign(state.settings,Object.fromEntries(Object.entries(message).filter(([key])=>key!=='action')));if(message.action==='select-item')state.selectedItem=structuredClone(find(message.id));if(message.action==='rename-item'){find(message.id).title=message.title;if(state.selectedItem?.id===message.id)state.selectedItem.title=message.title;}if(message.action==='collection-create')state.collections.push({id:'new',name:message.name,itemIds:[]});if(message.action==='collection-rename')state.collections.find(c=>c.id===message.id).name=message.name;if(message.action==='collection-delete')state.collections=state.collections.filter(c=>c.id!==message.id);if(message.action==='collection-membership'){const c=state.collections.find(c=>c.id===message.collectionId);c.itemIds=message.remove?c.itemIds.filter(id=>!message.itemIds.includes(id)):[...new Set([...c.itemIds,...message.itemIds])];}if(message.action==='collection-reorder')state.collections.find(c=>c.id===message.id).itemIds=message.itemIds;if(message.action==='transcript-select')state.selectedItem.transcript=state.selectedItem.transcriptTracks.find(track=>track.id===message.trackId);revision++;return {ok:true};}}};
    });
    await page.goto(`http://127.0.0.1:${server.address().port}/desktop.html`);
    await page.locator('#tour-dialog[open]').waitFor();await page.locator('#skip-tour').click();await page.waitForFunction(()=>window.testState().settings.tourState==='skipped');
    await page.locator('#create-collection').click();await page.locator('#collection-name').fill('Empty collection');await page.locator('#confirm-action').click();await page.getByRole('button',{name:'Empty collection',exact:true}).waitFor();
    await page.locator('[data-item-id="one"] .card-title').dblclick();await page.locator('#rename-title').fill('Renamed speech');await page.locator('#rename-title').press('Enter');await page.waitForFunction(()=>window.testState().library[0].title==='Renamed speech');
    await page.locator('[data-item-id="one"] .card-title').focus();await page.keyboard.press('F2');await page.locator('#rename-title').fill('Cancelled name');await page.keyboard.press('Escape');assert.equal(await page.locator('#workspace-view').isVisible(),false);
    await page.locator('[data-item-id="one"] input').check();await page.locator('[data-item-id="two"] input').check();await page.locator('#organize-selection').click();await page.getByRole('checkbox',{name:'Empty collection'}).check();await page.locator('#confirm-action').click();await page.waitForFunction(()=>window.testState().collections.find(c=>c.id==='new').itemIds.length===2);
    await page.getByRole('button',{name:'Actions for Empty collection'}).click();await page.getByRole('button',{name:'Delete collection…',exact:true}).click();await page.locator('#confirm-action').click();await page.waitForFunction(()=>!window.testState().collections.some(c=>c.id==='new'));assert.equal(await page.evaluate(()=>window.testState().library.length),3,'deleting collection does not delete library files');
    await page.locator('[data-item-id="one"] .card-open').click();await page.locator('.caption-cue').first().waitFor();assert.equal(await page.locator('#generate-transcript').isVisible(),false);await page.locator('#transcript-details>summary').click();assert.match(await page.locator('#caption-provenance').innerText(),/Generated transcript/);assert.equal(await page.locator('#load-captions').isVisible(),true);await page.locator('#transcript-details>summary').click();
    await page.locator('#caption-search').fill('Xin chào');assert.equal(await page.locator('.caption-cue').count(),1);assert.equal(await page.locator('#media-stage audio').evaluate(media=>media.paused),true,'opening media does not start sound');await page.locator('.cue-time').click();await page.waitForFunction(()=>document.querySelector('#media-stage audio').currentTime>=6);await page.locator('.current-cue').waitFor();await page.locator('#export-format').selectOption('vtt');await page.locator('#export-captions').click();assert.equal(await page.evaluate(()=>window.testMessages.at(-1).format),'vtt');await page.locator('#caption-search').fill('');await page.locator('#caption-language').selectOption('untimed');assert.equal(await page.locator('#export-format option[value=srt]').isDisabled(),true);assert.equal(await page.locator('.cue-time').first().isDisabled(),true);await page.locator('#caption-language').selectOption('generated');
    assert.equal(await page.evaluate(()=>window.testMessages.some(m=>m.action==='study-submit')),false,'opening existing transcript never submits speech');
    await page.locator('#caption-cues').hover();await page.mouse.wheel(0,800);await page.locator('#follow-cue').waitFor({state:'visible'});const stage=await page.locator('#media-stage').boundingBox();assert.ok(stage.y>=0&&stage.y+stage.height<=570,'player remains visible while transcript scrolls');
    const cueBox=await page.locator('#caption-cues').boundingBox();assert.ok(cueBox.height>=220&&cueBox.y+cueBox.height<=570,`transcript owns a bounded visible scroll panel of at least 220px (actual ${cueBox.height}px)`);
    if(process.env.FRAMEKEEP_SCREENSHOT_DIR){await mkdir(process.env.FRAMEKEEP_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.FRAMEKEEP_SCREENSHOT_DIR,'desktop-transcript-scrolled-synthetic.png')});}
    await page.locator('#theater-mode').click();assert.equal(await page.locator('.sidebar').isVisible(),false);await page.locator('#theater-mode').click();assert.equal(await page.locator('.sidebar').isVisible(),true);
    await page.locator('#back-library').click();assert.equal(await page.locator('#selection-count').innerText(),'2 selected');
    await page.getByRole('button',{name:'Examples',exact:true}).click();await page.locator('#play-collection').click();await page.locator('#playback-queue').waitFor({state:'visible'});assert.match(await page.locator('#item-title').innerText(),/Second recording/);await page.getByRole('button',{name:'Next',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#item-title').textContent==='Renamed speech');
    await page.locator('#nav-activity').click();await page.getByRole('button',{name:'Open media',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#item-title').textContent==='Renamed speech');
    await page.locator('#nav-settings').click();await page.locator('#appearance').selectOption('dark');await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await page.locator('#text-size').selectOption('20');await page.locator('#nav-help').click();await page.locator('#replay-tour').click();for(let i=0;i<4;i++)await page.locator('#next-tour').click();await page.waitForFunction(()=>window.testState().settings.tourState==='complete');
    await page.setViewportSize({width:500,height:740});await page.locator('#nav-library').click();await page.waitForFunction(()=>document.querySelector('#nav-library').getAttribute('aria-current')==='page');assert.ok(await page.locator('#nav-settings').isVisible());assert.ok(await page.locator('#nav-help').isVisible());assert.ok(await page.locator('#create-collection').isVisible());
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no narrow horizontal clipping');
    if(process.env.FRAMEKEEP_SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.FRAMEKEEP_SCREENSHOT_DIR,'desktop-narrow-dark-synthetic.png')});
    await page.setViewportSize({width:1108,height:570});
    await page.locator('.brand').click();await page.locator('[data-item-id="image"] .card-open').click();await page.locator('#image-zoom').waitFor({state:'visible'});assert.equal(await page.locator('#generate-transcript').isVisible(),false);assert.equal(await page.locator('.review-panel').isVisible(),false);
    await page.evaluate(()=>window.testChange(state=>{const item=state.library.find(i=>i.id==='two');item.capabilities.hasAudio=false;item.capabilities.speech=false;item.frames=[{id:'f1',time:1,previewUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDkQAAAAASUVORK5CYII='}];}));
    await page.locator('#back-library').click();await page.locator('[data-item-id="two"] .card-open').click();await page.locator('#review-frames').waitFor({state:'visible'});assert.equal(await page.locator('#generate-transcript').isVisible(),false);await page.locator('#fullscreen-media').click();await page.waitForFunction(()=>Boolean(document.fullscreenElement));await page.evaluate(()=>document.exitFullscreen());assert.equal(await page.locator('body').evaluate(body=>body.classList.contains('theater')),false);await page.locator('#review-frames').click();await page.getByRole('button',{name:'Enlarge frame 1'}).click();await page.locator('.frame-zoom').waitFor();await page.locator('#close-action').click();
    await page.evaluate(()=>window.testChange(state=>{const item=state.library.find(i=>i.id==='two');item.study={jobId:'visual-child',recipe:'visual',state:'evidence_ready'};state.jobs.push({id:'visual-child',sourceItemId:'two',action:'study',status:'evidence_ready',title:'Synthetic visual preparation'});}));
    await page.locator('#nav-activity').click();const visualChild=page.locator('[data-job-id="visual-child"]');await visualChild.waitFor();assert.equal(await visualChild.getByRole('button',{name:'Open transcript',exact:true}).count(),0,'silent visual output must not be mislabeled transcript');await visualChild.getByRole('button',{name:'Open frames',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#review-frames').getAttribute('aria-selected')==='true'&&!document.querySelector('#frames-panel').hidden);assert.equal(await page.locator('#frames-list .frame-preview').count(),1);
    await page.evaluate(()=>window.testChange(state=>{state.jobs.push({id:'orphan',sourceItemId:'gone',sourceUnavailable:true,sourceUnavailableReason:'Source media is missing from the library',status:'evidence_ready',title:'Preserved orphan job'});}));await page.locator('#nav-activity').click();await page.locator('[data-job-id="orphan"]').waitFor();assert.equal(await page.locator('[data-job-id="orphan"] button').isDisabled(),true);
    await page.locator('#nav-settings').click();await page.locator('#appearance').selectOption('light');await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await page.locator('#appearance').selectOption('system');
    await page.evaluate(()=>window.testChange(state=>{state.helper={status:'missing',error:'Synthetic disconnected component'};}));await page.locator('#retry-helper').click();await page.waitForFunction(()=>document.querySelector('#connection-label').textContent==='Check local connection');
    await page.locator('.brand').click();await page.locator('[data-item-id="one"] .card-open').click();await page.locator('.caption-cue').first().waitFor();
    assert.equal(await page.locator('.audio-artwork').count(),0,'missing artwork uses the neutral audio symbol');assert.equal(await page.locator('img[src$="/undefined"]').count(),0);
    await page.evaluate(()=>{window.polledPlayer=document.querySelector('#media-stage audio');window.testChange(state=>{state.selectedItem.transcriptTracks=[];state.selectedItem.transcript={status:'unavailable'};});});await page.locator('#caption-message').waitFor({state:'visible'});
    await page.evaluate(()=>window.testChange(state=>{state.selectedItem.transcriptTracks=[{id:'live-polled',source:'generated-live',status:'ready',language:'en',cues:[{start:0,end:2,text:'Settled live capture text after selection.'}],timed:true,sourceTiming:false}];state.selectedItem.transcript=state.selectedItem.transcriptTracks[0];}));
    await page.waitForFunction(()=>document.querySelector('#caption-cues').textContent.includes('Settled live capture text after selection.'));assert.equal(await page.locator('#generate-transcript').isVisible(),false,'persisted live transcript is reused');assert.match(await page.locator('#caption-language').innerText(),/Generated live transcript/);assert.equal(await page.evaluate(()=>window.polledPlayer===document.querySelector('#media-stage audio')),true,'transcript polling does not reload playback');
    assert.equal(await page.evaluate(()=>window.testMessages.some(m=>m.action==='study-submit')),false);
    assert.deepEqual(errors,[]);
  }finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
});
